import type {
  ChatMessage,
  Company,
  EvaluationQuestion,
  NotificationItem,
  Person,
  Report,
  Session,
} from "./types";

export const companies: Company[] = [
  {
    id: "c1",
    name: "Meridian Labs",
    kind: "startup",
    industry: "AI infrastructure",
    stage: "Series A",
    employees: "42",
    location: "Berlin / remote",
    website: "meridianlabs.io",
    summary:
      "Meridian Labs builds evaluation and observability tooling for applied AI teams. The company is raising follow-on capital and hiring senior product engineers.",
    focus: ["LLM evaluation", "Workflow orchestration", "Enterprise SOC2"],
  },
  {
    id: "c2",
    name: "Northbridge Capital",
    kind: "investor",
    industry: "Venture capital",
    employees: "28",
    location: "London",
    website: "northbridge.vc",
    summary:
      "Early-stage fund focused on B2B infrastructure, developer tools, and applied AI. Typical check size €1.5–4M.",
    focus: ["Developer tools", "AI infra", "Vertical SaaS"],
  },
  {
    id: "c3",
    name: "Helix Health",
    kind: "enterprise",
    industry: "Healthcare technology",
    employees: "1,200",
    location: "Amsterdam",
    website: "helixhealth.com",
    summary:
      "Helix Health is reviewing a vendor technical architecture before expanding a multi-year integration with Meridian Labs.",
    focus: ["Clinical workflows", "Data residency", "HIPAA / GDPR"],
  },
  {
    id: "c4",
    name: "Brightline Studio",
    kind: "agency",
    industry: "Product design & engineering",
    employees: "18",
    location: "Lisbon",
    website: "brightline.studio",
    summary:
      "Product studio specializing in design systems and frontend platforms for regulated industries.",
    focus: ["Design systems", "Frontend platforms", "Accessibility"],
  },
  {
    id: "c5",
    name: "Lumen Pay",
    kind: "startup",
    industry: "Fintech",
    stage: "Seed",
    employees: "14",
    location: "Stockholm",
    website: "lumenpay.co",
    summary:
      "Cross-border payouts for marketplaces. In Northbridge's pipeline for a seed follow-on.",
    focus: ["Payouts", "KYC orchestration", "Treasury"],
  },
];

export const people: Person[] = [
  {
    id: "u1",
    name: "Alex Rivera",
    email: "alex@meridianlabs.io",
    title: "Head of Product",
    role: "company",
    companyId: "c1",
    location: "Berlin",
    timezone: "Europe/Berlin",
    bio: "Leads product and hiring loops at Meridian Labs. Hosts client reviews, investor sessions, and technical interviews.",
    skills: ["Product strategy", "Hiring", "Technical writing"],
    avatarHue: 172,
    avatar: "/avatars/u1.jpg",
  },
  {
    id: "u2",
    name: "Jordan Hale",
    email: "jordan@northbridge.vc",
    title: "Partner",
    role: "investor",
    companyId: "c2",
    location: "London",
    timezone: "Europe/London",
    bio: "Leads Northbridge's infrastructure practice. Interested in defensible data moats and enterprise distribution.",
    skills: ["Diligence", "GTM", "Board work"],
    avatarHue: 222,
    avatar: "/avatars/u2.jpg",
  },
  {
    id: "u3",
    name: "Priya Shah",
    email: "priya.shah@helixhealth.com",
    title: "VP Engineering",
    role: "client",
    companyId: "c3",
    location: "Amsterdam",
    timezone: "Europe/Amsterdam",
    bio: "Owns vendor technical due diligence and architecture reviews for Helix Health's platform group.",
    skills: ["Architecture", "Security", "Vendor management"],
    avatarHue: 28,
    avatar: "/avatars/u3.jpg",
  },
  {
    id: "u4",
    name: "Sam Okonkwo",
    email: "sam.okonkwo@gmail.com",
    title: "Senior Full-Stack Engineer",
    role: "candidate",
    companyId: "c1",
    location: "Lagos / remote",
    timezone: "Africa/Lagos",
    bio: "Full-stack engineer with 8 years in TypeScript platforms. Interviewing for Staff Engineer, Platform.",
    skills: ["TypeScript", "Distributed systems", "React"],
    avatarHue: 258,
    avatar: "/avatars/u4.jpg",
  },
  {
    id: "u5",
    name: "Elena Voss",
    email: "elena@brightline.studio",
    title: "Founder & Design Lead",
    role: "candidate",
    companyId: "c4",
    location: "Lisbon",
    timezone: "Europe/Lisbon",
    bio: "Leads Brightline's engagement with Meridian Labs on the assessment workspace redesign.",
    skills: ["Product design", "Design systems", "Research"],
    avatarHue: 332,
    avatar: "/avatars/u5.jpg",
  },
  {
    id: "u6",
    name: "Marcus Chen",
    email: "marcus@meridianlabs.io",
    title: "Staff Engineer",
    role: "company",
    companyId: "c1",
    location: "Toronto",
    timezone: "America/Toronto",
    bio: "Runs technical interviews and system-design loops for platform hiring.",
    skills: ["Systems", "Interviewing", "Go"],
    avatarHue: 198,
    avatar: "/avatars/u6.jpg",
  },
  {
    id: "u7",
    name: "Nina Patel",
    email: "nina@meridianlabs.io",
    title: "CEO & Co-founder",
    role: "company",
    companyId: "c1",
    location: "Berlin",
    timezone: "Europe/Berlin",
    bio: "Founder leading the Series A process. Regularly presents to Northbridge and other funds.",
    skills: ["Fundraising", "Narrative", "Partnerships"],
    avatarHue: 12,
    avatar: "/avatars/u7.jpg",
  },
  {
    id: "u8",
    name: "David Krug",
    email: "david@northbridge.vc",
    title: "Principal",
    role: "investor",
    companyId: "c2",
    location: "London",
    timezone: "Europe/London",
    bio: "Supports Jordan on technical diligence and follow-on reviews for seed and Series A companies.",
    skills: ["Technical diligence", "Modeling"],
    avatarHue: 210,
    avatar: "/avatars/u8.jpg",
  },
  {
    id: "u9",
    name: "Hannah Lee",
    email: "hannah@meridianlabs.io",
    title: "Head of Talent",
    role: "company",
    companyId: "c1",
    location: "Berlin",
    timezone: "Europe/Berlin",
    bio: "Coordinates hiring loops, scorecards, and debrief sessions.",
    skills: ["Talent", "Enablement", "Operations"],
    avatarHue: 145,
    avatar: "/avatars/u9.jpg",
  },
  {
    id: "u10",
    name: "Omar Haddad",
    email: "omar.haddad@pm.me",
    title: "Backend Engineer",
    role: "candidate",
    companyId: "c1",
    location: "Paris",
    timezone: "Europe/Paris",
    bio: "Backend-leaning engineer interviewing for the data platform team.",
    skills: ["Python", "Kafka", "Postgres"],
    avatarHue: 42,
    avatar: "/avatars/u10.jpg",
  },
  {
    id: "u11",
    name: "Sofia Lindgren",
    email: "sofia@lumenpay.co",
    title: "CEO",
    role: "company",
    companyId: "c5",
    location: "Stockholm",
    timezone: "Europe/Stockholm",
    bio: "Founder pitching Lumen Pay's seed follow-on to Northbridge.",
    skills: ["Fintech", "Compliance", "Fundraising"],
    avatarHue: 280,
    avatar: "/avatars/u11.jpg",
  },
];

export const sessions: Session[] = [
  {
    id: "s1",
    title: "Series A technical & market review",
    type: "investor",
    status: "scheduled",
    hostId: "u7",
    companyId: "c1",
    startsAt: "2026-08-15T14:00:00+02:00",
    durationMin: 60,
    timezone: "Europe/Berlin",
    agenda: [
      "Traction and retention snapshot",
      "Product architecture walkthrough",
      "Competitive landscape",
      "Ask, use of funds, questions",
    ],
    modules: ["video", "screen", "whiteboard", "questions", "notes", "scorecard"],
    participants: [
      { personId: "u7", meetingRole: "presenter", cameraOn: true, micOn: true },
      { personId: "u1", meetingRole: "host", cameraOn: true, micOn: true },
      { personId: "u2", meetingRole: "evaluator", cameraOn: true, micOn: true },
      { personId: "u8", meetingRole: "observer", cameraOn: false, micOn: false },
    ],
    location: "remote",
    recordingEnabled: true,
  },
  {
    id: "s2",
    title: "Staff Engineer — live coding & systems",
    type: "interview",
    status: "live",
    hostId: "u6",
    companyId: "c1",
    startsAt: "2026-08-15T13:30:00+02:00",
    durationMin: 90,
    timezone: "Europe/Berlin",
    agenda: [
      "Introductions (5m)",
      "Coding exercise (35m)",
      "System design (30m)",
      "Candidate questions (10m)",
      "Internal debrief",
    ],
    modules: ["video", "coding", "whiteboard", "questions", "notes", "scorecard"],
    participants: [
      { personId: "u6", meetingRole: "host", joined: true, cameraOn: true, micOn: true },
      { personId: "u4", meetingRole: "candidate", joined: true, cameraOn: true, micOn: true },
      { personId: "u9", meetingRole: "observer", joined: true, cameraOn: false, micOn: false },
      { personId: "u1", meetingRole: "evaluator", joined: false, cameraOn: false, micOn: true },
    ],
    location: "remote",
    recordingEnabled: true,
  },
  {
    id: "s3",
    title: "Helix Health — architecture & risk review",
    type: "client_review",
    status: "scheduled",
    hostId: "u1",
    companyId: "c3",
    startsAt: "2026-08-18T10:00:00+02:00",
    durationMin: 75,
    timezone: "Europe/Amsterdam",
    agenda: [
      "Current integration map",
      "Data residency and DPA",
      "SLA and incident history",
      "Q3 expansion proposal",
    ],
    modules: ["video", "screen", "whiteboard", "questions", "scorecard", "notes"],
    participants: [
      { personId: "u1", meetingRole: "host", cameraOn: true, micOn: true },
      { personId: "u3", meetingRole: "evaluator", cameraOn: true, micOn: true },
      { personId: "u6", meetingRole: "presenter", cameraOn: true, micOn: true },
    ],
    location: "hybrid",
    recordingEnabled: true,
  },
  {
    id: "s4",
    title: "Brightline — design systems engagement eval",
    type: "freelancer",
    status: "completed",
    hostId: "u1",
    companyId: "c4",
    startsAt: "2026-08-08T11:00:00+02:00",
    durationMin: 60,
    timezone: "Europe/Berlin",
    agenda: ["Portfolio review", "Workshop exercise", "Commercial terms"],
    modules: ["video", "whiteboard", "questions", "scorecard", "notes"],
    participants: [
      { personId: "u1", meetingRole: "host" },
      { personId: "u5", meetingRole: "candidate" },
      { personId: "u9", meetingRole: "evaluator" },
    ],
    location: "remote",
    recordingEnabled: false,
  },
  {
    id: "s5",
    title: "Data platform — system design loop",
    type: "assessment",
    status: "completed",
    hostId: "u6",
    companyId: "c1",
    startsAt: "2026-08-06T16:00:00+02:00",
    durationMin: 70,
    timezone: "Europe/Berlin",
    agenda: ["System design prompt", "Trade-off discussion", "Scorecard debrief"],
    modules: ["video", "whiteboard", "questions", "scorecard", "notes"],
    participants: [
      { personId: "u6", meetingRole: "host" },
      { personId: "u10", meetingRole: "candidate" },
      { personId: "u1", meetingRole: "evaluator" },
    ],
    location: "remote",
    recordingEnabled: true,
  },
  {
    id: "s6",
    title: "Lumen Pay — seed follow-on intro",
    type: "investor",
    status: "scheduled",
    hostId: "u2",
    companyId: "c5",
    startsAt: "2026-08-21T09:30:00+02:00",
    durationMin: 45,
    timezone: "Europe/London",
    agenda: ["Founder intro", "Unit economics", "Next steps"],
    modules: ["video", "screen", "questions", "notes"],
    participants: [
      { personId: "u2", meetingRole: "host" },
      { personId: "u11", meetingRole: "presenter" },
      { personId: "u8", meetingRole: "evaluator" },
    ],
    location: "remote",
    recordingEnabled: false,
  },
  {
    id: "s7",
    title: "Candidate debrief — Staff loop",
    type: "interview",
    status: "draft",
    hostId: "u9",
    companyId: "c1",
    startsAt: "2026-08-16T17:00:00+02:00",
    durationMin: 30,
    timezone: "Europe/Berlin",
    agenda: ["Scorecard alignment", "Offer recommendation"],
    modules: ["video", "scorecard", "notes"],
    participants: [
      { personId: "u9", meetingRole: "host" },
      { personId: "u6", meetingRole: "evaluator" },
      { personId: "u1", meetingRole: "evaluator" },
    ],
    location: "remote",
    recordingEnabled: false,
  },
];

export const reports: Report[] = [
  {
    id: "r1",
    sessionId: "s4",
    title: "Brightline engagement recommendation",
    summary:
      "Elena presented a coherent design-system approach and a realistic 8-week plan. Craft quality is high. Commercials are slightly above benchmark but justified by accessibility depth.",
    recommendation: "yes",
    overall: 4.4,
    dimensions: [
      { id: "d1", label: "Craft quality", score: 5, max: 5 },
      { id: "d2", label: "Process fit", score: 4, max: 5 },
      { id: "d3", label: "Communication", score: 5, max: 5 },
      { id: "d4", label: "Commercials", score: 3, max: 5 },
      { id: "d5", label: "Risk", score: 4, max: 5 },
    ],
    publishedAt: "2026-08-08T15:40:00+02:00",
    visibility: "shared",
  },
  {
    id: "r2",
    sessionId: "s5",
    title: "Omar Haddad — system design result",
    summary:
      "Strong streaming mental model and clear ownership boundaries. Needed prompting on back-pressure and exactly-once semantics. Recommend next loop: coding + hiring manager.",
    recommendation: "lean_yes",
    overall: 3.8,
    dimensions: [
      { id: "d1", label: "Problem framing", score: 4, max: 5 },
      { id: "d2", label: "Architecture", score: 4, max: 5 },
      { id: "d3", label: "Trade-offs", score: 3, max: 5 },
      { id: "d4", label: "Communication", score: 4, max: 5 },
      { id: "d3b", label: "Depth", score: 4, max: 5 },
    ],
    publishedAt: "2026-08-06T18:10:00+02:00",
    visibility: "private",
  },
];

export const seedChat: ChatMessage[] = [
  {
    id: "m1",
    sessionId: "s2",
    authorId: "u6",
    body: "I'll paste the coding prompt in the assessment tab. Feel free to ask clarifying questions before you start.",
    at: "2026-08-15T13:32:00+02:00",
  },
  {
    id: "m2",
    sessionId: "s2",
    authorId: "u4",
    body: "Sounds good — I'll assume we can use TypeScript and the standard library.",
    at: "2026-08-15T13:33:00+02:00",
  },
  {
    id: "m3",
    sessionId: "s2",
    authorId: "u9",
    body: "I'll stay muted. Scoring privately in the notes panel.",
    at: "2026-08-15T13:34:00+02:00",
    private: true,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Live now",
    body: "Staff Engineer interview with Sam Okonkwo is in progress.",
    at: "2026-08-15T13:30:00+02:00",
    href: "/sessions/s2/room",
  },
  {
    id: "n2",
    title: "Upcoming in 40 minutes",
    body: "Series A review with Northbridge Capital.",
    at: "2026-08-15T13:20:00+02:00",
    href: "/sessions/s1",
  },
  {
    id: "n3",
    title: "Report published",
    body: "Brightline evaluation report is ready to share.",
    at: "2026-08-08T15:40:00+02:00",
    href: "/reports/r1",
  },
];

export const questionsByType: Record<Session["type"], EvaluationQuestion[]> = {
  investor: [
    { id: "q1", prompt: "Is the market large enough and expanding?", kind: "scale", answer: 4 },
    { id: "q2", prompt: "How defensible is the technical moat?", kind: "scale", answer: 4 },
    { id: "q3", prompt: "Team quality for this stage", kind: "scale", answer: 5 },
    {
      id: "q4",
      prompt: "Investment stance",
      kind: "choice",
      options: ["Lead", "Follow", "Pass", "Need more data"],
      answer: "Need more data",
    },
    { id: "q5", prompt: "Open questions for founders", kind: "text" },
  ],
  client_review: [
    { id: "q1", prompt: "Architecture fitness for our scale", kind: "scale", answer: 4 },
    { id: "q2", prompt: "Security & compliance posture", kind: "scale", answer: 3 },
    { id: "q3", prompt: "Delivery confidence this quarter", kind: "scale", answer: 4 },
    {
      id: "q4",
      prompt: "Go-forward recommendation",
      kind: "choice",
      options: ["Expand", "Maintain", "Pilot", "Exit"],
      answer: "Expand",
    },
    { id: "q5", prompt: "Risks to escalate", kind: "text" },
  ],
  interview: [
    { id: "q1", prompt: "Problem solving", kind: "scale", answer: 4 },
    { id: "q2", prompt: "Code quality", kind: "scale", answer: 4 },
    { id: "q3", prompt: "System design", kind: "scale", answer: 3 },
    { id: "q4", prompt: "Communication", kind: "scale", answer: 5 },
    {
      id: "q5",
      prompt: "Level recommendation",
      kind: "choice",
      options: ["Senior", "Senior+", "Staff", "Below bar"],
      answer: "Senior+",
    },
    { id: "q6", prompt: "Private interviewer notes", kind: "text" },
  ],
  freelancer: [
    { id: "q1", prompt: "Craft / portfolio quality", kind: "scale", answer: 5 },
    { id: "q2", prompt: "Process and collaboration", kind: "scale", answer: 4 },
    { id: "q3", prompt: "Commercial fit", kind: "scale", answer: 3 },
    {
      id: "q4",
      prompt: "Engagement recommendation",
      kind: "choice",
      options: ["Engage", "Hold", "Decline"],
      answer: "Engage",
    },
  ],
  assessment: [
    { id: "q1", prompt: "Correctness", kind: "scale", answer: 4 },
    { id: "q2", prompt: "Depth of reasoning", kind: "scale", answer: 4 },
    { id: "q3", prompt: "Trade-off awareness", kind: "scale", answer: 3 },
    { id: "q4", prompt: "Overall", kind: "choice", options: ["Strong yes", "Yes", "Lean yes", "No"] },
  ],
};

export const defaultScorecard = [
  { id: "sc1", label: "Signal strength", score: 4, max: 5 },
  { id: "sc2", label: "Communication", score: 4, max: 5 },
  { id: "sc3", label: "Ownership", score: 3, max: 5 },
  { id: "sc4", label: "Role fit", score: 4, max: 5 },
];

export const roleUsers: Record<Person["role"], string> = {
  company: "u1",
  investor: "u2",
  client: "u3",
  candidate: "u4",
};

export function getPerson(id: string) {
  return people.find((p) => p.id === id);
}

export function getCompany(id: string) {
  return companies.find((c) => c.id === id);
}

export function getSession(id: string) {
  return sessions.find((s) => s.id === id);
}

export function getReport(id: string) {
  return reports.find((r) => r.id === id);
}
